spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Clpetition?serverTimezone=Asia/Seoul&useLegacyDatetimeCode=false&characterEncoding=UTF-8
    username: root
    password:
  jpa:
    generate-ddl: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        format_sql: true
        default_batch_fetch_size: 50
        jdbc:
          time_zone: Asia/Seoul
instagram:
  callback-uri: "https://localhost:8080/auth/instagram/callback"