spring:
  servlet:
    multipart:
      max-file-size: 10MB # 요청한 파일 한 개의 크기
      max-request-size: 10MB # 요청한 파일 전체의 크기

jwt:
  token:
    secret-key: ${jwt.secret}
  access:
    expiration: 31536000000 # 365일
    header: Authorization
  refresh:
    expiration: 1209600000 # 2주
    header: Authorization-refresh

cloud:
  aws:
    s3:
      bucket: ${s3.bucket}
    credentials:
      access-key: ${s3.access.key}
      secret-key: ${s3.secret.key}
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false

logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: prod